### ISSUE TITLE
can't run the script in python2 with dependencies installed

### ISSUE THREAD

**Issue by docfate111** [dongyangwu/p-joker#6]
i installed type annotations for python2
```
python2 -m pip install typing
```
but then 
```
$ python2 p-joker.py
Traceback (most recent call last):
  File "p-joker.py", line 11, in <module>
    from iokit_kextclass.kext_analyzer import *
  File "/Users/thelshell/hacking/p-joker/iokit_kextclass/kext_analyzer.py", line 17, in <module>
    from TypeParser import *
  File "/Users/thelshell/hacking/p-joker/iokit_kextclass/TypeParser.py", line 1, in <module>
    import cxxfilt
  File "/Users/thelshell/Library/Python/2.7/lib/python/site-packages/cxxfilt/init.py", line 26
    def init(self, mangled_name: Union[str, bytes]) -> None:
                                   ^
SyntaxError: invalid syntax
```
even though in the code
```
from typing import Union, Sequence
```
also cxxfilt has f-strings in the package and other features that don't work(found out after I commented out all the type annotations :( ) with the MacOS verison of python2.7

**Comment by droe** [comment]
Workaround: `python2.7 -m pip install 'cxxfilt==0.2.0'`
